### PR TITLE
Improve status, enable, disable

### PR DESCRIPTION
**Pull request by stodorovic**
* Load _wp-cache-config.php_ ( `$GLOBALS['wp_cache_config_file']` ) instead of _wp-cache-phase1.php_ because this file will create output buffer and it's possible that caching will be disabled. Also, it's issue if `WPSC_HTTP_HOST` isn't set, then caching is also disabled. It's better to load only config file to prevent false result (and avoid creating output buffer).
* Use `$cache_enabled` because it's main variable which enable/disable caching. Related code: https://github.com/Automattic/wp-super-cache/blob/master/wp-cache.php#L994-L997
* Similar for enable/disable - https://github.com/Automattic/wp-super-cache/blob/master/wp-cache.php#L585-L596. Current code disable only super cache, but wp-cache still works.

I'm planning to improve this code, but for now it's minimal change. I've opened Automattic/wp-super-cache#431 and when we merge Automattic/wp-super-cache#499, I'll try to improve code in WPSC. After these changes, I'll try to submit more PRs here. Please send me your feedback.

### CODE REVIEW

**Comment by schlessera** [comment]
Hi @stodorovic,
While going through the changes needed for WP-CLI v2, I just noticed that we dropped the ball for this PR.

Are these changes still needed? If so, I'll work on merging them into the latest master once #21 has been merged.

**Comment by stodorovic** [comment]
Hi @schlessera,
Changes are still needed because there are a lot of changes in WPSC, but this PR is outdated. Also current code in `wp-super-cache-cli` is outdated. Probably it's time to big update.

I'm planning to split it into two new PRs after you merge #21 and we merge [WPSC #592](https://github.com/Automattic/wp-super-cache/pull/592).

First PR will add methods __maybe_load_files_ and __maybe_load_wpsc_config_ for backward compatibility with previous versions. They will be called from `__construct` or maybe exists better way ? (hook or something like this? ).  Method __maybe_load_wpsc_config_ will populates globals from config file (if they aren't already set) and all commands will have  prepared environment.

Second PR will fix commands.

I'm happy to we together improve `wp-super-cache-cli` :smile:

**Comment by schlessera** [comment]
Thanks for the feedback, @stodorovic!

If I understand correctly, we can close this PR to open fresh ones?

**Comment by stodorovic** [comment]
Thanks @schlessera!

Closed in favor of #22.

**Pull request closed without merging**
